*Variablen Label LFS für files 2003 bis 2018 - für zusammengfasste elemente, daher auch einzelne elemente doppelt, da es ab 2011 namensänderungen der variable gab

label variable hhseqnum "Sequence number in the household"
label variable national "Nationality"
label variable sex "Sex"
label variable yearesid "Years of residence in this Member State"
label variable countryb "Country of birth"
label variable proxy "Nature of participation in the survey"
label variable wstator "Labour status during the reference week"
label variable nowkreas "Reason for not having worked at all though having a job"
label variable stapro "Professional Status"
label variable signisal "Continuing receipt of the wage or salary"
label variable nace1d "Economic activity of the local unit"
label variable na111d "Economic activity of the local unit"
label variable isco3d "Occupation"
label variable is883d "Occupation"
label variable countryw "Country of place of work"
label variable regionw "Region of place of work"
label variable ystartwk "Year in which person started working for this employer or as self-employed"
label variable mstartwk "Month in which person started working for this employer or as self-employed"
label variable ftpt "Full-time / Part-time distinction"
label variable temp "Permanency of the job"
label variable tempdur "Total duration of temporary job or work contract of limited duratio"
label variable hwusual "Number of hours per week usually worked"
label variable hwactual "Number of hours actually worked during the reference week"
label variable hwoverp "Paid overtime in the reference week in the main job"
label variable hwoverpu "Unpaid overtime in the reference week in the main job"
label variable hourreas "Main reason for hours actually worked during the reference week being different"
label variable wishmore "Wish to work usually more than the current number of hours"
label variable hwwish "Number of hours that the person would like to work in total"
label variable lookoj "Looking for another job and reasons for doing so"
label variable exist2j "Existence of more than one job or business"
label variable stapro2j "Professional status (in the second job)"
label variable nace2j1d "Economic activity of the local unit (in the second job)"
label variable na112j1d "Economic activity of the local unit (in the second job)"
label variable hwactua2 "Number of hours actually worked during the reference week in the second job"
label variable existpr "Existence of previous employment experience"
label variable yearpr "Year in which person last worked"
label variable monthpr "Month in which person last worked"
label variable stapropr "Professional status in last job"
label variable stapropr "Professional status in last job"
label variable nacepr1d "Economic activity of the local unit in which person last worked"
label variable na11pr1d "Economic activity of the local unit in which person last worked"
label variable iscopr3d "Occupation of last job"
label variable is88pr3d "Occupation of last job"
label variable seekwork "Seeking employment during previous four weeks"
label variable seektype "Type of employment sought"
label variable seekdur "Duration of search for employment"
label variable methoda "Contacted public employment office to find work"
label variable methodb "Contacted private employment agency to find work"
label variable methodc "Applied to employers directly"
label variable methodd "Asked friends, relatives, trade unions, etc"
label variable methode "Inserted or answered advertisements in newspapers or journals"
label variable methodf "Studied advertisements in newspapers or journals"
label variable methodg "Took a test, interview or examination"
label variable methodh "Looked for land, premises or equipment"
label variable methodi "Looked for permits, licences, financial resources"
label variable methodj "Awaiting the results of an application for a job"
label variable methodk "Waiting for a call from a public employment office"
label variable methodl "Awaiting the results of a competition for recruitment to the public sector"
label variable methodm "Other method used"
label variable wantwork "Willingness to work for person not seeking employment"
label variable availble "Availability to start working within two weeks"
label variable educstat "Student or apprentice in regular education during the last 4 weeks (formal"
label variable educlevl "Level of this education or training"
label variable couratt "Attendance to taught learning activities (non-formal education) in the last 4 we"
label variable courlen "Number of hours spent on all taught learning activities within the last 4 weeks"
label variable hat97lev "Highest educational attainment level (97)"
label variable hat11lev "Highest educational attainment level (11)"
label variable hatvoc "Orientation of this level"
label variable educvoc "Orientation of this education"
label variable refyear "Year of survey"
label variable refweek "Reference week"
label variable intweek "Interview week"
label variable country "Country"
label variable region "Region of household"
label variable degurba "Degree of urbanisation"
label variable hhtype "Type of household"
label variable hhinst "Type of institution"
label variable intwave "Sequence number of the survey wave"
label variable intquest "Questionnaire used"
label variable coeff "Yearly weighting factor"
label variable quarter "Fixed reference quarter"
label variable year "Fixed reference year"
label variable rem "Reference month"
label variable hhpriv "Classification of individuals (private household members)"
label variable age "Age of interviewed person"
label variable ageresid "Age at which person last established their usual residence in the country"
label variable ilostat "ILO work status"
label variable startime "Time since person started to work"
label variable leavtime "Time since person last worked"
label variable leavclas "Time since person last worked (classes)"
label variable durune "Duration of unemployment"
label variable na11s "Economic activity by sector (NACE Rev 1)"
label variable isco1d "Occupation (coded 1 digit)"
label variable is881d "Occupation (coded 1 digit)"
label variable na112js "Economic activity in second job by sector (NACE Rev 1)"
label variable na11prs "Economic activity in previous job by sector (NACE Rev 1)"
label variable iscopr1d "Occupation previous job (coded 1 digit)"
label variable is88pr1d "Occupation previous job (coded 1 digit)"
label variable educ4wn "Education or training received during previous four weeks (formal + non formal)"
label variable hatlev1d "Level of education (3 levels)"
label variable hhlink "Relationship to reference person in the household"
label variable hhspou "Sequence number of spouse or cohabiting partner"
label variable hhfath "Sequence number of father"
label variable hhmoth "Sequence number of mother"
label variable marstat "Marital status"
label variable supvisor "Supervisory responsibilities"
label variable sizefirm "Number of persons working at the local unit"
label variable wayjfoun "Involvement of the public employment office at any"
label variable ftptreas "Reasons for the part-time work"
label variable tempreas "Reasons for having a temporary job/work contract of"
label variable tempagcy "Contract with a temporary employment agency"
label variable shiftwk "Shift work"
label variable evenwk "Evening work"
label variable nightwk "Night work"
label variable satwk "Saturday work"
label variable sunwk "Sunday work"
label variable waymore "Way that a person who wants to work more hours"
label variable homewk "Working at home"
label variable lookreas "Reasons for looking for another job"
label variable leavreas "Main reason for leaving last job or business"
label variable seekreas "Reasons for not searching an employment"
label variable avaireas "Reasons for not being available to start working within 2 weeks"
label variable preseek "Situation immediately before person started to seek employment (or was waiting f"
label variable needcare "Need for care facilities"
label variable register "Registration at a public employment office"
label variable mainstat "Main labour status"
label variable educfild "Field of this education or training (until 2013)"
label variable courpurp "Purpose of the most recent taught learning activity"
label variable courfild "Field of the most recent taught learning activity"
label variable courworh "Did the most recent taught learning activity take place during paid working hour"
label variable hatfield "Field of this level"
label variable hatyear "Year when this level was successfully completed"
label variable wstat1y "Situation with regard to activity one year before survey"
label variable stapro1y "Professional status one year before survey"
label variable nace1y1d "Economic activity one year before survey (coded 1 digit)"
label variable na111y1d "Economic activity one year before survey (coded 1 digit)"
label variable countr1y "Country of residence one year before survey"
label variable region1y "Region of residence (within Member State) one year before survey"
label variable incdecil "Monthly (take home) pay from main job (deciles)"
label variable eseg2d "European Socio-economic Groups (ESeG)"
label variable hwustrai "Usual number of hours of training per week"
label variable methfw "Main method used to find work"
label variable purp4w "Purpose of the training received during previous 4 weeks"
label variable lentr4w "Total length of training"
label variable hhpers "Definition of children and adults"
label variable hhparent "Presence of the father and/or mother of the person in the same household"
label variable hhpartnr "Presence of the partner of the person in the same household"
label variable hhchildr "Presence of the children of the person in the same household"
label variable hatlfath "Education level of the father (if he lives in the same household)"
label variable hatlmoth "Education level of the mother (if she lives in the same household)"
label variable hhnbpers "Total number of persons in the household (whatever the age)"
label variable hhnb0014 "Number of children in the household (aged less than 15 years)"
label variable hhnbold "Number of persons aged 65 or older in the household"
label variable hhnbchld "Number of children in the household (aged less than 25 years)"
label variable hhnbch2 "Number of persons between 0 and 2 years in the household"
label variable hhnbch5 "Number of persons between 3 and 5 years in the household"
label variable hhnbch8 "Number of persons between 6 and 8 years in the household"
label variable hhnbch11 "Number of persons between 9 and 11 years in the household"
label variable hhnbch14 "Number of persons between 12 and 14 years in the household"
label variable hhnbch17 "Number of children between 15 and 17 years (in the household)"
label variable hhnbch24 "Number of children between 18 and 24 years (in the household)"
label variable hhageyg "Age of the youngest child in the household (aged less than 25 years)"
label variable hhage14 "Age of the youngest child in the household (aged less than 15 years)"
label variable hhcomp "Household type (families; aggregated household composition)"
label variable hhnbwork "Number of employed persons in the household (aged 15 years and more)"
label variable hhnbempl "Number of employed adults in the household (aged 15 years and more)"
label variable hhnbunem "Number of unemployed adults in the household (aged 15 years and more)"
label variable hhnbinac "Number of inactive adults in the household (aged 15 years and more)"
label variable hhwkstat "Working status of adults living in the same household"
